In [4]:
import pandas as pd

data = pd.read_excel('/Users/user/Documents/Work_Studies/FAO_Projects/PPR/data/ppr_outbreaks-adis.xls')

data.head()

,Reference,Country/Territory,Type,Disease name,Local Authority Unit (LAU),Submitted on,Administrative division level 1,Administrative division level 2,Administrative division level 3,Outbreak occurring inside an already restricted zone,...,Category 6,Subcategory 6,Test name 6,Test type 6,Laboratory name 6,Laboratory type 6,Species 6,Result date 6,Result type 6,Reported to
0,GR-PPR-2024-00072,Greece,Primary,Peste des petits ruminants virus (Inf. with),NaN,2024-09-17,Thessaly and Central Greece,Thessaly,Larissa,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EU
1,GR-PPR-2024-00071,Greece,Primary,Peste des petits ruminants virus (Inf. with),NaN,2024-09-13,Thessaly and Central Greece,Thessaly,Tempi,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EU
2,GR-PPR-2024-00070,Greece,Primary,Peste des petits ruminants virus (Inf. with),NaN,2024-09-13,Thessaly and Central Greece,Thessaly,Tempi,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EU
3,GR-PPR-2024-00069,Greece,Primary,Peste des petits ruminants virus (Inf. with),NaN,2024-09-12,"Peloponnese, Western Greece and the Ionian Isl...",Peloponnese,Sikyona,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EU
4,GR-PPR-2024-00068,Greece,Primary,Peste des petits ruminants virus (Inf. with),NaN,2024-09-12,"Peloponnese, Western Greece and the Ionian Isl...",Peloponnese,Sikyona,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EU

In [39]:
# Drop empty columns
data.dropna(how="all", axis=1, inplace=True)

In [41]:
data.shape

(152, 36)

In [44]:
data.columns

Index(['Reference', 'Country/Territory', 'Type', 'Disease name',
       'Local Authority Unit (LAU)', 'Submitted on',
       'Administrative division level 1', 'Administrative division level 2',
       'Administrative division level 3',
       'Outbreak occurring inside an already restricted zone', 'Latitude',
       'Longitude', 'Species 1', 'Susceptible 1', 'Cases 1', 'Dead 1',
       'Killed 1', 'Slaughtered 1', 'Outbreak year', 'Suspicion/Start date',
       'Confirmation date', 'Status Continuing/Resolved', 'Suspicion',
       'Clinical signs', 'Diagnostic tests', 'Necropsy', 'Category 1',
       'Subcategory 1', 'Test name 1', 'Test type 1', 'Laboratory name 1',
       'Laboratory type 1', 'Species 1.1', 'Result date 1', 'Result type 1',
       'Reported to'],
      dtype='object')

In [46]:
columns = ['Country/Territory', 'Latitude', 'Longitude', 'Administrative division level 2','Species 1', 'Susceptible 1', 'Cases 1', 'Dead 1',
       'Killed 1', 'Slaughtered 1', 'Confirmation date']

data = data[columns]
data.head()

,Country/Territory,Latitude,Longitude,Administrative division level 2,Species 1,Susceptible 1,Cases 1,Dead 1,Killed 1,Slaughtered 1,Confirmation date
0,Greece,39.731,22.409,Thessaly,Sheep/goats (mixed herd),380.0,NaN,NaN,NaN,NaN,2024-09-16
1,Greece,39.777,22.563,Thessaly,Sheep/goats (mixed herd),850.0,NaN,NaN,NaN,NaN,2024-09-12
2,Greece,39.774,22.561,Thessaly,Sheep/goats (mixed herd),1000.0,NaN,NaN,NaN,NaN,2024-09-12
3,Greece,37.901,22.334,Peloponnese,Sheep/goats (mixed herd),246.0,12.0,NaN,NaN,NaN,2024-09-11
4,Greece,37.912,22.330,Peloponnese,Sheep,100.0,5.0,NaN,NaN,NaN,2024-09-11

In [48]:
data.to_csv('/Users/user/Documents/Work_Studies/FAO_Projects/PPR/data/clean_data.csv', index=False)